ScriptInvaders/responsible

package.json
=> (feat) Initialize npm and package.json.

client/pleaseDelete.txt, server/apis/toDelete.txt, server/models/toDelete.txt, test/test_apis/deleteMe.txt, test/test_models/deleteME.txt
(feat) Adding basic file structure
=> (feat) Adding basic file structure

.gitignore, dist/index.html
(feat) Improve dist/ and gitignore to upload the index.hmtl but ignore our webpacked bundle.
=> closes #32

client/actionCreators/ride.js, client/actionCreators/user.js, client/actionCreators/view.js, client/app.js, client/containers/ProfileContainer.js, client/reducers/childReducer.js, client/reducers/rootReducer.js, package.json
Feat/redux infrastructure 
Initial infrastructure for redux. Many many changes to come.
=> closes #30

client/app.js, client/components/DriverItemList.js, client/components/TopNavBarMiddleButton.js, client/containers/Profile.js, client/containers/TopNavBar.js
Change some naming of our redux containers.
=> closes #40

server/apis/chat-api.js, server/apis/ride-api.js, server/apis/user-api.js, server/index.js, server/models/model-helper.js, server/models/user.js, server/server-helpers.js, test/server/test_apis/user-api.js_test.js, test/server/test_apis/user-api_test.js, test/test-helper.js
Fixed syntax using new JSCS linter
=> (fix) Syntax/fix

client/app.js, client/components/CancelRideButton.js, client/components/ProfileButton.js, client/components/RiderInfoItem.js, client/components/SettingIcon.js, client/components/TopNavBarMiddleButton.js, client/components/TopNavBarRightButton.js, client/containers/TopNavBar.js, webpack.config.js
* (feat) Check and view for main page (not rider and not driver)
* (feat) Check and view for rider's driver page (rider but not yet confirmed and matched with driver)
* (feat) Check and view for driver's confirmed page (driver and matched/confirmed with a rider)
* (feat) Settings button always visible
* (feat) Drive button visible on main page
* (feat) Profile button visible on main and confirming page
* (feat) Cancel Ride button visible on matched ride page
* Still to complete: Rider's confirmed page (view driver)
=> TopNavBar Progress -#29

client/actionCreators/user.js, client/actionCreators/view.js, client/app.js, client/components/DriveButton.js, client/components/FriendItem.js, client/components/FriendItemList.js, client/components/RiderInfoItem.js, client/components/TopNavBarMiddleButton.js, client/containers/TopNavBar.js, client/reducers/childReducer.js
DO NOT MERGE - need to rebase again.
Feat/top nav bar actions
Fix TopNavBar component's rendering. By passing our props in through the constructor, subsequent renders only saw those initial props.
=> closes #42

server/apis/user-api.js, server/models/user.js, test/server/test_apis/user-api_test.js
Fixed functionality to find user by id. Returns correct user. Still having the migrations lock problem, might need to be an issue to take care of soon. closes #62
=> (feat) added a test. Can find user by user ID.  closes #62

client/public/styles/skeleton.css
* (feat) CSS styling for profile page
** To-do: Apply infinite scroll (later)
=> Closes -#65 Profile Page doesn't look as terrible

client/app.js, client/components/ProfileButton.js, client/components/ProfileInfoItemList.js, client/components/Splash.js
* (fix) Whole profile button is clickable (not just text)
=> Closes #56

client/actionCreators/ride.js, client/components/TopNavBarRightButton.js, client/containers/TopNavBar.js, client/reducers/ride.js
=> Feat/cancel button actions #79

lib/schema.js, server/models/user.js, test/server/test_apis/user-api_test.js
Changed user models to work with new database schema. Figured out the hard way what migrations are. Made some mild changes to the schema to make our rides table make sense.
=> (fix) fixed tests to work with new database

migrations/20160311121609_schemaupdate.js, migrations/20160311121621_schemaupdate.js, server/apis/rides-api.js, server/apis/user-api.js, server/index.js, server/models/rides.js, server/models/user.js, test/server/test_apis/ride-api_test.js
added a test to make sure rides can be made with valid user_id
=> (feat) added the first ride test

client/actionCreators/ride.js, client/components/BottomNavBarButton.js, client/components/ConfirmLocationButton.js, client/containers/BottomNavBar.js, client/containers/Main.js, client/containers/TopNavBar.js, client/initialState.js, client/reducers/ride.js
Confirm ride is connected
cancel ride button fixed.
=> Feat/reduxify bottom bar closes #83

server/apis/rides-api.js, server/index.js, server/models/rides.js, test/server/test_apis/ride-api_test.js
=> (feat) ride tests working

server/apis/message-api.js, server/apis/rides-api.js, server/index.js, server/models/message.js, server/models/rides.js, test/server/test_apis/message-api_test.js, test/server/test_apis/ride-api_test.js
Defined ride routes. Designed tests for create, get, and delete rides. Edited some of the tests to be more concise with their actions. 
Defined msg routes. Still working on what that is going to look like. Tomorrow i'll be able to finish more of the backend and how that all works out, as well as design some tests for that. 
Bottom line: dealing with multiple relational databases gets pretty tricky pretty quick. In order to enter this info without a bunch of errors, you have to post to the user table, then to the rides table, and then to the message table. Almost done with writing the tests and working on the backend stuff, hopefully be able to finish tomorrow.
=> (feat) ride tests, msg tests, models, and much more

client/components/CancelRideButton.js, client/components/CatchARideButton.js, client/components/DriveButton.js, client/components/DriverInfoItem.js, client/components/DriverItemList.js, client/components/Logo.js, client/components/ProfileButton.js, client/components/SettingIcon.js, client/components/Splash.js, client/components/TopNavBarMiddleButton.js, client/components/TopNavBarRightButton.js, client/components/UserImage.js, client/containers/BottomNavBar.js, client/containers/Main.js, client/containers/Profile.js, client/containers/Root.js, client/containers/TopNavBar.js, client/initialState.js, client/public/styles/skeleton.css, package.json
* (cleanup) Refactor all containers to functions
* (cleanup) Remove extraneous code: i.e., extra 'require' statements, unnecessary comments, etc.
=> Refactor Containers: Closes #91 and #90

client/reducers/ride.js, test/client/reducers/rideReducer-spec.js, test/client/reducers/userReducer-spec.js
=> (feat) Write receive and request match tests for rideReducer closes #94

lib/schema.js, server/apis/message-api.js, server/apis/ride-api.js, server/index.js, server/models/message.js, test/server/test_apis/message-api_test.js, test/server/test_apis/ride-api_test.js
Starting API configuration is complete. All api routes have tests which check for get, create, and delete. Models completed for basic functionality of routes and database calls. Schema adjusted to incorporate usernames for message body. Ride id is associated with messages as well so we can get rides by id later on.
=> (feat) completed starting API configuration

server/models/message.js
=> (fix) changed user to message in message model

client/components/TopNavBarRightButton.js, package.json, test/client/reducers/routeReducer-spec.js
very useful for passing props in react components!
=> Implement object rest operator transpiling

.travis.yml
Reverts ScriptInvaders/responsible#138
=> Revert "changes made to travis file to create a test database"

.travis.yml, package.json, test/client/actionCreators-spec.js
updated the travis file to run client test, database testing commented out for time being
=> travis file updated

client/actionCreators/user.js, client/app.js, client/lib/sockets.js, client/reducers/user.js, client/reducers/userInfo.js, dist/index.html, package.json, server/index.js
* The first thoughts on sockets are up and connecting.
* async user action creators are setup.
=> Feat/user info actions #148

client/actionCreators/chat.js, client/components/Chat/MessageItemList.js, client/containers/Chat.js, client/reducers/cancelRide.js, client/reducers/ride.js, client/reducers/rideMessages.js
* (feat) Chat box takes text submissions
* (feat) Submissions dispatch action to update messages and show new messages
** To-do: Style chat bar, reformat!
=> Chat accepts submissions! Closes #16

client/containers/Chat.js, client/public/styles/skeleton.css
* (feat) CSS doesn't look like total poop
** To-do: someone else make this look better
=> (feat) Basic CSS styling of message submit

client/actionCreators/user.js, client/app.js, client/components/SignoutButton.js, client/components/TopNavBar/Friends/FriendButton.js, client/components/TopNavBar/Friends/FriendItemList.js, client/components/TopNavBar/RightButton.js, client/components/TopNavBar/Settings/SettingIcon.js, client/containers/Friends.js, client/containers/Profile.js, client/containers/Settings.js, client/containers/TopNavBar.js, client/initialState.js, client/reducers/user.js
* (feat) Settings menu has: profile, friends, signout buttons
* (feat) Profile button routes to profile page
** To-Do: populate profile page with actual info (and not just user image)
* (feat) Friends button routes to friends page and displays list of friends
** To-Do: create form to let user add friends;
* (feat) Signout button resets some state to null/false (anything on user state)
**To-Do: Reroute to auth page after signout (assuming checks will be in place to check auth that will redirect)
=> Settings Menu - Closes #118

server/models/friends.js, server/models/rides.js, test/lib/seed_test.js, test/server/test_models/friends_test.js
Server can find available drivers closes #130 
Server can now find which drivers are available who are friends closes #165 
Server can now find riders who are friends closes #166 
Server knows about ongoing rides #132 
Added tests for all using generator functions and seed data. Pretty gnarly stuff. Thanks for your help amigo! @JonKrone
=> (feat) Friends models working and tested

client/actionCreators/chat.js, client/actionCreators/ride.js, client/actionCreators/user.js, client/initialState.js, client/reducers/cancelRide.js, client/reducers/confirmRide.js, client/reducers/fetchRide.js, client/reducers/ride.js, client/reducers/rideMessages.js
* In previous PRs, I wrote some actionCreators that returned unhandled action types. This PR adds some reducer functionality to handle those actions.
* Add a few console.errors to make sure we see notice errors from the server.
=> Feat/checking forgotten actions closes #182

lib/schema.js, server/apis/user-api.js, server/lib/auth.js, server/models/user.js
Title describes the content well, check the file changes for details - there's some comments.
closes #184
=> Server merges OAuth + DB user on POST to /user

.travis.yml, client/actionCreators/ride.js, client/components/BottomNavBar/BottomButton.js, client/components/MapView.js, client/components/TopNavBar/CancelRideButton.js, client/containers/Main.js, client/containers/TopNavBar.js, client/initialState.js, client/lib/fetchHelpers.js, client/lib/socketListeners.js, client/reducers/fetchRide.js, client/reducers/ride.js, client/reducers/riders.js, lib/schema.js, server/apis/rides-api.js, server/apis/user-api.js, server/models/rides.js, server/models/user.js, server/server-helpers.js, test/lib/seed_test.js, test/server/test_apis/ride-api_test.js
This is a merging of 4-5 main blocks of feature work combining to allow the cancellation of rides.
* Cancel rides: user can cancel an in-progress ride or a request for a ride.
- on DELETE to /rides, server determines how to cancel a ride or ride request, responding with 200 on success
- server emits socket messages to alert the partner to remove the rider or ride. 
- database riders schema augmented to cascade deletions
- client cancelClick handlers pass correct information to actionCreators
=> Feat/delete to riders #194

.jscsrc, client/actionCreators/user.js, client/components/BottomNavBar/BottomButton.js, client/initialState.js, client/models/Github.js, client/reducers/userInfo.js, lib/schema.js, server/apis/user-api.js
* (Feat) State updates after sign-in!
** To-do: Pull friends/other info on signin
=> Sign-in populates state Closes #140

.jscsrc, client/actionCreators/user.js, client/components/BottomNavBar/BottomButton.js, client/initialState.js, client/models/Github.js, client/reducers/userInfo.js, lib/schema.js, server/apis/user-api.js
Reverts ScriptInvaders/responsible#207
=> Revert "Sign-in populates state Closes #140"

client/components/BottomNavBar/ConfirmLocationButton.js, client/components/Splash/DriveButton.js, client/components/Splash/RideButton.js, client/components/TopNavBar/Logo.js, client/components/TopNavBar/Settings/SettingIcon.js, client/containers/Main.js, client/containers/Splash.js, client/containers/TopNavBar.js, client/public/styles/normalize.css, client/public/styles/skeleton.css, client/public/styles/styles.css, dist/index.html
Reverts ScriptInvaders/responsible#206
=> Revert "css styling done to splash page"

client/actionCreators/user.js, client/containers/Main.js, client/models/Github.js, client/reducers/userInfo.js, server/apis/user-api.js
* (feat) Refixed state: populates on user signin
=> (feat) ReFixed state! Closes #140 Closes #134 Closes #128

client/components/RiderItem.js, client/containers/Main.js, client/containers/RiderItemList.js, client/containers/Riders.js, client/initialState.js
Added rider component, a rider list that is populated from rider items, and a way to get riders from state into our riders list. Cool stuff! first stab at react, but im catching on to some of the tricks of what is going on. Pretty wild stuff!
=> (feat) Feat/riders list

client/actionCreators/chat.js, client/actionCreators/user.js, client/containers/Chat.js, client/lib/socketListeners.js, client/lib/socketSetup.js, client/reducers/user.js, server/apis/rides-api.js, server/index.js, server/lib/ioConfig.js, server/models/rides.js
DO NOT MERGE YET please thanks
* Infrastructure for action creators to emit events to specific channels
- Clients join chanell '55' on connection.
- Clients communicate
* server functionality to emit to select channels
=> Feat/separate socket handling #203

client/containers/TopNavBar.js, server/apis/rides-api.js
** contains the changes for the two previous PRs tonight. Review those PRs before merging please! **
* Simple fix for cancelling an in-progress ride.
=> Fix/delete rider closes #216

server/apis/user-api.js, server/models/friends.js
=> Implement POST to /user/friends for adding a friend

server/apis/user-api.js, server/models/friends.js
Reverts ScriptInvaders/responsible#219
=> Revert "Implement POST to /user/friends for adding a friend"

client/actionCreators/user.js, client/containers/Friends.js, client/reducers/userInfo.js, server/models/user.js
* (feat) Friends updates after siginin!
* (feat) Friends will then re-render (after siginin)
* (feat) -- No errors if there are no friends in the database
** To-do: let users add friends!
=> Friends updates on signin Closes #211

client/actionCreators/user.js, client/app.js, client/components/Chat/MessageItemList.js, client/containers/Friends.js, client/containers/Profile.js, client/reducers/user.js, client/reducers/userInfo.js, server/apis/user-api.js, server/models/friends.js, server/models/user.js
* (feat) User is able to add friends by username, first name, or last name
* (feat) Friendship inserted into database
* (feat) State will update with new friend addition
** To-do: Error catching - fix errors for no friends found
** To-do: Do not let db add multiple friendships of the same kind (don't continually add same friend)
=> Friends! Closes #113 and Closes #114

client/initialState.js
Fix user address on initialState to match database
Testing Travis (it said it failed :()
=> Test/Fix InitialState

client/actionCreators/user.js, client/components/BottomNavBar/BottomButton.js, client/components/DriverItem.js, client/components/TopNavBar/Friends/FriendItem.js, client/containers/Main.js, client/initialState.js, client/models/Github.js, client/models/users.js, client/reducers/userInfo.js, lib/schema.js, lib/seeds/users.js, server/models/user.js
* (fix) Changed names in database to 'name'  (not first_name and last_name)
* (fix) Refactored code to match
=> Refactor names - Closes #226

client/actionCreators/user.js, client/app.js, client/containers/Login.js, client/containers/Main.js, client/lib/authConfig.js, client/lib/storeConfig.js
* (feat) App will check (via middleware) if user is signed in or not
* (feat) If user not signed in, app will redirect to signin page
* (feat) SUPER basic signout butt (WILL REFACTOR!) will clear cache and redirect to signin page
** To-do: Refactor Top Nav Bar to move the login in buttons into signin page
** To-do: Make signout button not look stupid
=> Auth Checks! Closes #125 and Closes #124 and Closes #122

client/components/SignoutButton.js, client/containers/Main.js, client/containers/Settings.js
* (feat) Signout button does not look stupid anymore
=> (feat) Signout button lives in Settings Closes #242 and Closes #204

client/actionCreators/ride.js, client/components/BottomNavBar/BottomButton.js, client/components/MapView.js, client/containers/BottomNavBar.js, client/containers/Chat.js, client/containers/RiderItemList.js, client/initialState.js, client/lib/socketListeners.js, lib/seeds/users.js, package.json, server/apis/rides-api.js, server/apis/user-api.js, server/lib/ioConfig.js, server/models/friends.js, server/models/user.js, test/lib/seed_test.js
* Bunches of changes culminating in new riders emitting a ride request to all of their friends
* Client emits the list of friends to check, for ease.
* Re-tweak a bunch of socket ids on server side to emit to the proper channels.
* Testing client-side messaging now easier by emitting messages only to your ride partner.
* Finding a user by name refactored to support new naming scheme.
* Tweak initial state for consistency and working with messaging and client-side testing.
=> Feat/fetch ride emits rider #235

client/containers/Login.js, client/containers/Main.js
* (feat) Woo, login buttons on their own page
=> (feat) Refactor login in buttons to own page Closes #243

client/actionCreators/drive.js, server/models/rides.js
=> (fix) Now with location parsing!

client/app.js, client/reducers/rideRouting.js
location changes are dispatched only when our current location is different than our stored location by a more than 2e-7, or 0.0000002
* Also accidentally tracked (forgot to save when switching branches, didn't realize till submitting PR) file changes for a branch I am working on. As of now, these changes don't affect anything.
=> (feat) tolerant location changes

client/actionCreators/ride.js, client/components/RiderItem.js, client/components/SignoutButton.js, client/containers/RiderItemList.js, client/containers/Riders.js, client/initialState.js, client/reducers/drivers.js, client/reducers/ride.js
* (feat) Driver can click on rider to confirm
* (feat) Front-end connected with already-built back-end
=> Driver can accept rider! Closes #201

client/actionCreators/drive.js, client/actionCreators/ride.js, client/actionCreators/user.js, client/app.js, client/components/MapView.js, client/containers/TopNavBar.js, client/lib/socketListeners.js, client/reducers/ride.js, client/reducers/rideRouting.js, lib/seeds/riders.js, server/lib/ioConfig.js
* skeleton for socket distribution of updated locations between riders/driver
* Contains bug fix for displaying seeded riders.
=> Feat/ride location sharing closes #255

client/components/RiderItem.js, client/containers/RiderItemList.js
* (feat) Driver's rider list shows names and avatars
* (feat) Still able to click on the user and dispatch the correct action
** To-do: Styling!! Avatars are not styled anymore...
=> Filter friends Closes #200

client/models/Github.js, server/models/friends.js
* Server will not try to make friends when users are already friends.
=> Bug/friend duplication closes #225

client/actionCreators/ride.js, client/components/BottomNavBar/BottomButton.js, client/components/RiderItem.js, client/containers/Main.js, client/containers/RiderItemList.js, client/initialState.js, client/lib/socketListeners.js, client/reducers/confirmRide.js, client/reducers/drivers.js, server/apis/rides-api.js, server/models/rides.js, server/models/user.js
This is two branches of changes. One debugging mission between Kim and I that culminated in re-writing/fixing the User model's findFriends, and the other trying to flesh out the accept-ride flow from driver-> server -> driver and rider so that their ride.match state is complementary and pulls from their friend's list and is filled with the location information from acceptance.
Tomorrow will be a big day for rider+driver communication! Lots of details to flesh out but we're getting closer and closer to a full user flow.
=> Feat/inform rider of match #271

client/actionCreators/user.js, client/components/SignoutButton.js, client/containers/Profile.js, client/initialState.js, client/lib/authConfig.js, client/models/Github.js, client/reducers/userInfo.js
* (feat) Local storage stores user information
* (feat) App checks for github token and profile on state
* (feat) If no profile on state, app will repopulate state from local storage information
* (feat) Signout clears information from local storage
=> (fix) Auth Bus Closes #264 Closes #265

client/components/End.js, client/containers/Main.js
* (feat) New page (components/end.js) has random DUI/DWI facts
** To-do: connect it with things.
=> (feat) End page with random DUI/DWI facts

client/actionCreators/ride.js, client/components/TopNavBar/CompleteRideButton.js, client/components/TopNavBar/RightButton.js, client/containers/Main.js, client/containers/TopNavBar.js, client/initialState.js, client/reducers/ride.js, client/reducers/rideRouting.js
Reverts ScriptInvaders/responsible#280
=> Revert "(feat) Working complete Ride Button"

client/actionCreators/ride.js, client/components/TopNavBar/CompleteRideButton.js, client/components/TopNavBar/RightButton.js, client/containers/Main.js, client/containers/TopNavBar.js, client/initialState.js, client/reducers/ride.js, client/reducers/rideRouting.js
Reverts ScriptInvaders/responsible#281
=> Revert "Revert "(feat) Working complete Ride Button""

client/reducers/userInfo.js, lib/seeds/riders.js, lib/seeds/rides.js, lib/seeds/users.js, server/models/user.js
* (feat) Local storage will update after a friend is added - fixes reloading issues
=> (fix) Local storage updates after friend addition Closes #284

client/containers/Login.js, client/lib/authConfig.js, client/models/Google.js, client/models/users.js, server/apis/user-api.js
* (feat) Users can signin in Google now!
=> Google signin Closes #287

client/actionCreators/user.js, client/containers/Profile.js
* (feat) Redirects to profile page if no address in database
* (fix) Changing address will update local storage
* (feat) Address is editable
** To-do: Deliver some sort of message to user if there is no address
** To-do: Clean up profile page
=> Profile has address form - Closes #119

knexfile.js, lib/seeds/users.js, server/models/user.js
* (fix) Names are properly capitalized going in to database
* (fix) Query using ILIKE for case-sensitivity
=> Capitalized Correctly - Closes #293

client/components/BottomNavBar/BottomButton.js, client/components/BottomNavBar/ConfirmLocationButton.js, client/components/Profile/ProfileButton.js, client/components/SignoutButton.js, client/components/Splash/DriveButton.js, client/components/Splash/RideButton.js, client/components/TopNavBar/CancelRideButton.js, client/components/TopNavBar/CompleteRideButton.js, client/components/TopNavBar/EndDrivingButton.js, client/components/TopNavBar/Friends/FriendButton.js, client/components/TopNavBar/Logo.js, client/components/TopNavBar/PickUpButton.js, client/components/TopNavBar/Settings/SettingIcon.js, client/components/UserImage.js, client/containers/BottomNavBar.js, client/containers/Profile.js, client/containers/TopNavBar.js, client/public/styles/styles.css, dist/index.html
We have a lot of style changes here guys. The whole app has been overhauled to use react-bootstrap instead of bulma. There have been many changes to the classNames on every react component. I have taken care of many merge conflicts already, but would not be surprised if there are more to come. Definitely make a branch off your master and rebase onto that, because I don't know what is going to happen. Hopefully things go well and the styling makes the difference. It is reactive to changes in size, so you should test with mobile in your chrome browser.
=> No more bulma

client/actionCreators/ride.js, client/actionCreators/user.js, client/containers/Friends.js, client/containers/TopNavBar.js, client/initialState.js, client/reducers/userInfo.js, server/models/friends.js
* (feat) Alert displays if user adds friend they already have or friend that does not exist
* (feat) If there is an error, state will reset after 2 seconds
=> Friend Errors Closes #291

client/containers/Friends.js, client/containers/Profile.js, client/containers/TopNavBar.js
* (feat) User will see warning prompt for address if no address is found on state
=> (feat) Prompt user for address with alert

client/containers/TopNavBar.js
* (fix) Added in one bit to change the mouse pointer
=> (fix) Fix pointer on logo

client/reducers/user.js
* rider is redirected to splash page state on being dropped off
=> (feat) Rider is redirected to splash page on being dropped off.

client/components/RiderItem.js, client/containers/RiderItemList.js, client/containers/TopNavBar.js, client/public/styles/styles.css
=> Style colors settings and beyond

client/components/BottomNavBar/BottomButton.js, client/components/Chat/MessageItemList.js, client/components/MapView.js, client/initialState.js, client/reducers/drivers.js, client/reducers/rideRouting.js
* Added keys to messages in MessageItemList and rider markers for MapView.
* Additionally debug and fix rider state isConfirmed status not reseting on a completed ride.
=> (fix) React component keys and Rider state bugfix.

client/containers/TopNavBar.js
* simple swapping of brand and settings menu
=> (fix) swap position of logo + settings

client/components/RiderItem.js, client/components/TopNavBar/Friends/FriendItem.js, client/components/UserImage.js, client/containers/RiderItemList.js, client/public/styles/styles.css, lib/seeds/riders.js, lib/seeds/users.js
Added horizontal scroll box, as well as some styling.
=> Style rider list

client/containers/TopNavBar.js, client/public/styles/styles.css
* (fix)(style) TopNavBar only takes one row, regardless of mobile or not. Also centers logo
=> TopNavBar Fixed

client/components/TopNavBar/Friends/FriendItemList.js, client/containers/Friends.js, client/containers/TopNavBar.js, client/public/styles/styles.css, server/models/friends.js
* (style) Center friends, form submit, header on friends page
* (feat) Add alert to add friends if none are found
* (fix) Change error messages to be more user-friendly
* (fix) Fix centering on logo to be more responsive
* (style) Refactor settings button to hamburger-style
=> Friends View Revamped

client/actionCreators/ride.js, client/actionCreators/user.js, client/components/TopNavBar/Friends/FriendItemList.js, client/containers/Friends.js, client/containers/Main.js, client/containers/Profile.js, client/initialState.js, client/reducers/confirmRide.js, client/reducers/ride.js, client/reducers/user.js, client/reducers/userAddress.js, client/reducers/userInfo.js
* (feat) Add success alert on changing address
* (feat) Add success alert on adding friends
* (feat) Add success alert for driver when choosing a match
** To-do: Connect friend alert message with socket to alert user if someone else added them
** To-do: Connect ride alert with socket to alert rider when driver has picked them up
=> Success Messaging

client/components/RiderItem.js, client/components/UserImage.js, client/public/styles/styles.css
Rider Item list is centered, and has horizontal scroll
=> Rider item list centered

client/components/RiderItem.js, client/components/UserImage.js, client/public/styles/styles.css
Rider Item list is centered, and has horizontal scroll
=> Revert "Rider item list centered"

client/components/RiderItem.js, client/components/UserImage.js, client/public/styles/styles.css
Did it again. Some how in the revert i lost it all.
=> style-redid the centering on the rider list

client/actionCreators/ride.js, client/containers/Main.js, client/containers/TopNavBar.js, lib/seeds/users.js
* (feat) Success message after matching with rider (as driver)
* (fix) Fix seed data capitalization
* (fix) Fix accessibility error in navbar
** To-do: Test alert messages with driver (as rider)
=> Success Messages

client/containers/Chat.js, client/initialState.js, client/public/styles/styles.css
* (fix) Linting errors in Chat container
* (fix) Remove dummy messages from InitialState
* (fix) Inconsistencies with chat bubbles
* (style) Alert text is centered
=> Small Fixes

client/public/styles/styles.css
=> (fix) tweak chat styles

client/components/RiderItem.js, client/containers/TopNavBar.js, client/public/styles/styles.css
Resize, Clean, and optimize for iPhone 6
=> New styles

lib/seeds/friends.js, lib/seeds/riders.js, lib/seeds/users.js
* db changes for presentation screen caps
=> (fix) database updates for presentation

server/models/user.js, test/lib/seed_test.js, test/server/test_apis/ride-api_test.js, test/server/test_apis/user-api_test.js, test/server/test_models/friends_test.js, test/server/test_models/user_test.js
=> User tests

server/models/rides.js, test/server/test_models/friends_test.js, test/server/test_models/message_test.js, test/server/test_models/rides_test.js
=> Test ride test
